-- Lists all genres with the number of linked shows
SELECT TV_GENRES.NAME AS genre, COUNT(TV_SHOW_GENRES.SHOW_ID) AS number_of_shows
FROM TV_GENRES
JOIN TV_SHOW_GENRES
ON TV_GENRES.ID = TV_SHOW_GENRES.GENRE_ID
GROUP BY TV_GENRES.NAME
ORDER BY number_of_shows DESC;
